version: "2.0"

services:

  letsencrypt:
    image: tobi312/rpi-certbot:latest
    command:  bash -c "sleep 6 && certbot certonly --standalone -d gwatch.ga -d www.gwatch.ga --email todachuy2406@gmail.com --text --agree-tos --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
    entrypoint: ""
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/pirate/docker/rpi-lemp/letsencrypt:/etc/letsencrypt
    networks:
      webgis:
        aliases:
          - certbot

networks:
  webgis:
